version: "3.9"

services:
  mongodb:
    image: mongo:5.0
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/app/data/db
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    restart: on-failure
    environment:
      - UPTIME_KUMA_URL=http://localhost:3001/api/push/T4nk2B3y72?status=up
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ~/apps/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: always
